services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
